### ISSUE TITLE
After select the Departure Date & Time, the arrival will be able to sync the same Date & Time with Departure( To reduce less scroll)

### ISSUE THREAD

**Issue by Annasalihin** [zencomputersystems/eClaim#1223]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by Annasalihin** [comment]
Screen Shot : ![Bugs Image](http://i66.tinypic.com/27yveie.jpg)

**Comment by steelburn** [comment]
Reduced user scroll by changing default arrival time to be the same as departure time, and by not showing earlier time at all.
