### ISSUE TITLE
Travel Date & Time : To reduce the number of minutes to every 5 minutes

### ISSUE THREAD

**Issue by Annasalihin** [zencomputersystems/eClaim#1224]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by Annasalihin** [comment]
Screen Shot : ![Bugs Image](http://i65.tinypic.com/rlc8s7.jpg)

**Comment by steelburn** [comment]
Changed to every 15 minutes.
