### ISSUE TITLE
Added a new fields in a table

### ISSUE THREAD

**Issue by Pratap-Singh** [zencomputersystems/eClaim#37]
Table:- user_info
    In this table i added a new fields.
    BRANCH,
    EMPLOYEE_TYPE,
    APPROVER1,
    APPROVER2,
    EMPLOYEE_STATUS,
    CONFIRMATION_DATE

**Comment by steelburn** [comment]
Please remove approver1 & approver2 from that table.
If you need approvers, create new approver table.
